<!doctype html>
<html class="no-js" lang="en">
<?php echo view("head"); ?>

<body>
   <!-- preloader start here -->
   <div class="preloader">
      <div class="preloader-inner">
         <div class="preloader-icon">
            <span></span>
            <span></span>
         </div>
      </div>
   </div>
   <!-- preloader ending here -->
   <!-- scrollToTop start here -->
   <a href="#" class="scrollToTop"><i class="icofont-rounded-up"></i></a>
   <!-- scrollToTop ending here -->
   <!-- begin header -->
   <?php echo view("header"); ?>
   <!-- end header -->
   <!-- ===========pageheader Section start Here========== -->
   <section class="pageheader-section" style="background-image: url(<?php echo site_url() . "assets/front/img/bg.jpg"; ?>);">
      <div class="container">
         <div class="section-wrapper text-center">
            <h2 class="pageheader-title">Términos & condiciones</h2>
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb justify-content-center mb-0">
                  <li class="breadcrumb-item">
                     <a href="/">Inicio</a>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">
                     Términos & condiciones
                  </li>
               </ol>
            </nav>
         </div>
      </div>
   </section>
   <!-- ===========pageheader Section Ends Here========== -->
   <!-- ============ shop Section start Here========== -->
   <div class="shop padding-top padding-bottom">
      <div class="container">
         <div class="shop__wrapper">
            <div class="product__single">
               <div class="row gx-4 gy-5">
                  <div class="col-md-12">
                     <p>Los Términos y Condiciones que se expresan en este contrato constituyen las condiciones de uso y privacidad del servicio de la plataforma Mundo Network y demás servicios agregados que se prestan a los usuarios en la actualidad y a futuro por la empresa Mundo Network en su sitio web www.MundoNetwork.com, tanto en su aplicación web a través del dominio MundoNetwork.com como en su versión móvil para Android y IOS.</p>
                     <p><b>Consideraciones Preliminares</b></p>
                     <p> El usuario comprende y acepta libre, pleno y sin reservas todos y cada uno de los términos y condiciones que le asisten en este contrato, por simple causal de uso del servicio Mundo Network y demás servicios agregados, de los cuales será responsable sobre su cumplimiento. Si el usuario no está de acuerdo en su totalidad sobre lo dispuesto, no podrá hacer uso de los servicios prestados por Mundo Network.</p>
                     <p> Si el usuario es representante de alguna organización empresarial, da por entendido que está facultado para actuar en nombre de ella y, en consecuencia, obligarla frente a Mundo Network a aceptar todas las obligaciones derivadas de este contrato.</p>
                     <p> El usuario que acepte el presente contrato, debe ser legalmente apto para celebrarlo según lo permita su autonomía de la voluntad y las leyes que le sean aplicables en su país y, por tanto, da por entendido a Mundo Network que conoce previamente si está o no en capacidad de celebrar contratos a nombre propio o en representación de alguna organización.</p>
                     <p> Los términos y condiciones podrán ser modificados total o parcialmente, sin previo aviso o autorización por parte del usuario. Los cambios e implementaciones tendrán vigencia a partir del momento mismo en que sean publicados o insertados en el sitio web de Mundo Network o desde que sean notificados al usuario por cualquier medio; en todo caso, sea cual fuere el medio de divulgación, operarán con el primer aviso que obtenga.</p>
                     <p><b>Descripción del Servicio</b></p>
                     <p>La empresa Mundo Network en la actualidad presta el servicio de la plataforma Mundo Network, en cada uno de sus planes, bajo dos modalidades: la primera, gratuita con una expiración de 7 días calendario contados a partir de la creación de la cuenta y la segunda, de pago con las condiciones seleccionadas al momento de contratar la cuenta por parte del titular o usuario, quien adquiere una licencia de uso no exclusiva, mundial y temporal e intransferible para usar el sistema de información.</p>
                     <p>El servicio de Mundo Network se inicia desde el momento de registrar una cuenta en su sitio web, una vez el titular de la misma y/o los usuarios hayan aceptado las condiciones expresadas en este contrato. El servicio consiste en el uso del software Mundo Network y demás servicios agregados, disponibles en el dominio MundoNetwork.com, orientados a la gestión de la información académica y administrativa en las instituciones de educación, pudiendo incluir de acuerdo al plan elegido las siguientes funcionalidades: Gestión de clientes potenciales, inscripciones y matrículas, gestión de documentos digitales, gestión de grupos, cursos, horarios, aulas y docentes, gestión de homologaciones, habilitaciones y planes de mejoramiento, evaluación por competencias o evaluación cuantitativa, educación virtual integrada, administración de contenido dinámico, publicación de anuncios, cuestionarios, foros, tareas, gestión de tesorería (recibos, facturación, boletas), ingresos y egresos, gestión de cartera, órdenes de pago, créditos educativos, pagarés, proyección de recaudos, cuadres de caja, paz y salvos (constancias de no adeudo), gestión de egresados, ofertas laborales, informes académicos estadísticos, constancias, certificados y formatos de calidad, gestión de solicitudes, creación, recopilación y administración de encuestas institucionales.</p>
                     <p>El usuario manifiesta tener pleno conocimiento de los servicios por los que está o no está pagando a la hora de usar alguno de los planes que ofrece Mundo Network, quien no se hará responsable en ningún caso por los errores cometidos por el usuario a la hora de elegir su plan.</p>
                     <p>Mundo Network da por entendido que el titular de la cuenta y los usuarios conocen cualquier cambio que se haga en la configuración de ésta. Mundo Network no se responsabilizará por la pérdida de información que ocurra por fuerza mayor, caso fortuito o hecho de un tercero tal y como se explica bajo el título “Operación del Sitio”.</p>
                     <p>Mundo Network garantiza al usuario el libre acceso a la plataforma para gestionar la información allí disponible, bajo condiciones normales; sin embargo, el usuario acepta que existan circunstancias técnicas por las que ésta información puede llegar a estar inaccesible de manera temporal y por lo tanto exonera a Mundo Network de cualquier tipo de responsabilidad por este hecho, bajo el entendido de que esto puede obedecer a mantenimientos o actualizaciones del sistema, o a limitaciones inherentes al estado de la tecnología en la actualidad.</p>
                     <p><b>Alcance y nivel de servicio</b></p>
                     <p>En condiciones normales, la plataforma Mundo Network y sus servicios agregados tienen un “down time” de aproximadamente el 1%, de tal manera que se encuentran disponibles el 99% del tiempo.</p>
                     <p>Mundo Network realizará todas las actividades que considere pertinentes para que la plataforma se encuentre disponible para su uso, mas no lo garantiza, toda vez que pueden existir eventos como: daños en las comunicaciones, actos de terceros, mantenimiento o reestructuración de la aplicación, entre otros, que escapen al control y responsabilidad de Mundo Network. No obstante lo anterior, Mundo Network garantiza que la aplicación estará disponible en circunstancias normales vía Internet, según lo anunciado, no requiriendo de instalaciones en equipos situados en el domicilio del usuario, siempre y cuando el mismo se encuentre activo para el uso de la aplicación, haga uso de las credenciales correctas de su cuenta y las condiciones de prestación del servicio de conexión a Internet por parte de cada proveedor lo permitan, no siendo responsabilidad de Mundo Network el no funcionamiento o el funcionamiento deficiente causado por el servicio de banda ancha contratado por el usuario.</p>
                     <p>Mundo Network se encuentra facultado, sin necesidad de autorización por parte del usuario, para realizar las modificaciones o ajustes sobre la estructura técnica de la base de datos y de las aplicaciones que hacen parte del sistema Mundo Network, toda vez que ésta es de propiedad de la empresa Mundo Network, aunque éste último reconoce que la información es de propiedad del usuario. Igualmente, Mundo Network procurará informar oportunamente aquellos cambios que estime convenientes para evitar incomodidades o eventuales perjuicios en el procesamiento de la información.</p>
                     <p>Mundo Network brindará un servicio postventa 100% virtual al usuario administrador, de acuerdo al plan elegido, a través de diferentes canales de atención y herramientas tecnológicas como: manual en línea, chat, asistencia remota, atención telefónica o email, los días no feriados, de lunes a viernes de 8:00 a.m. a 5:00 p.m en jornada continua y los sábados de 8:00 a.m. a 12 m., de acuerdo a la zona horaria de referencia UTC-05.</p>
                     <p><b>Medios de Pago</b></p>
                     <p>El titular de la cuenta o usuario podrá elegir el plan y periodo de pago al momento de realizar el primer pago. Según el periodo elegido: semestral o anual, el próximo cobro se realizará transcurrido el tiempo de dicho periodo contratado contado a partir del primer pago efectuado.</p>
                     <p>El pago es anticipado y el usuario acepta que se realicen cobros recurrentes según los periodos elegidos. Además se compromete a notificar a Mundo Network en caso tal de que no quiera que se genere el siguiente cobro, mínimo 2 días hábiles antes de su próxima fecha de cobro.</p>
                     <p>En caso de que el usuario no notifique a Mundo Network, con anticipación sobre su deseo de no generar el cobro recurrente, este tendrá 5 días hábiles para pedir la devolución del dinero conforme el derecho de retracto previsto en el Estatuto del Consumidor.</p>
                     <p>Mundo Network ofrece los medios de pago que se reseñan en su página web. Sin embargo, para acceder a sus servicios a través de algunos de estos sistemas de pago, puede ser necesario registrar por parte del titular de la cuenta alguna información, como por ejemplo un número de cuenta o tarjeta de crédito expedida por parte de una entidad financiera que se encuentre vigente, para poder realizar el cobro por los servicios prestados en la plataforma online disponible en el dominio MundoNetwork.com o en la aplicación móvil. Si existen retenciones de cualquier tipo estas tendrán que ser asumidas por el usuario.</p>
                     <p>Mundo Network es consciente que poseer información de tarjetas de crédito o cuentas bancarias de los usuarios es delicado. Por lo tanto, está comprometido con mantener esta información segura y aislada de usos inadecuados.</p>
                     <p>Mundo Network da por hecho que la información de la tarjeta de crédito ingresada para crear una cuenta es conocida por el titular de la cuenta por lo tanto no se hace responsable por el uso inadecuado de tarjetas de crédito al momento de esta ser usada para registrar una cuenta, entendiéndose como uso irresponsable, la falsificación y suplantación de la identidad del titular la cuenta.</p>
                     <p>Mundo Network, por lo tanto, se abstiene de llevar a cabo todo tipo de actos tendientes a la verificación de los datos personales del usuario para confrontarlos con los registrados en su tarjeta de crédito pues asume que quien brinde los mismos es su propio titular y por ello conoce datos a los que no tiene acceso cualquier persona, además de no tener bases de datos con las cuales confrontar tal información.</p>
                     <p>No obstante lo anterior, el usuario autoriza a Mundo Network a llevar a cabo cualquier verificación o consulta de los datos suyos en cualquier base de datos, centrales de información y riesgo y cualquier otra fuente de información que le brinde historia sobre la forma en la que atiende sus compromisos financieros y crediticios, tanto en el ámbito nacional como en el internacional.</p>
                     <p>El usuario afirma bajo la gravedad de juramento, que no está incluido en la Lista Clinton y que sus ingresos no tienen relación con ningún tipo de actos de aquellos que la legislación española e internacional determinan para el lavado de activos, narcotráfico, terrorismo ni otro delito y que son adquiridos de manera lícita.</p>
                     <p><b>Enlaces de Terceras Partes</b></p>
                     <p>Ciertos contenidos, productos o servicios disponibles en el sistema Mundo Network podrían incluir material de terceras partes. Determinados enlaces en este servicio podrían direccionar al usuario a sitios web de terceras partes que no están afiliadas con Mundo Network quien no se responsabiliza de examinar o evaluar su contenido o exactitud y no garantiza, ni se obliga o responsabiliza por cualquier material, productos o servicios de terceros.</p>
                     <p>Mundo Network no se hace responsable de cualquier daño o daños relacionados con la adquisición o utilización de bienes, servicios, recursos, contenidos, o cualquier otra transacción realizada en conexión con sitios web de terceros. El usuario es el directo responsable en revisar cuidadosamente las políticas y prácticas de terceros y asegurarse de entenderlas antes de participar en cualquier transacción. Quejas, reclamos, inquietudes o preguntas con respecto a productos de terceros deben ser dirigidas a la tercera parte.</p>
                     <p><b>Logos</b></p>
                     <p>El usuario autoriza a Mundo Network el uso de los logos de las instituciones de educación participantes, en la página web: www.MundoNetwork.com y portafolio de servicios, sección clientes, con la única intención de presentar la relación comercial vinculante entre las partes.</p>
                     <p><b>Política de privacidad</b></p>
                     <p>Funciones publicitarias de Google Analytics implementadas en Mundo Network utiliza las audiencias de remarketing de Google Analytics para su uso en Google AdWords y DoubleClick Bid Manager, esto con el fin de publicar campañas de remarketing dirigidas a sus usuarios. El usuario acepta que su información sea tratada para efectos de Big Data y por lo tanto permite que Mundo Network utilice estas herramientas con fines estadísticos.</p>
                     <p><b>Modo de uso de las cookies</b></p>
                     <p>Mundo Network, Mediante la instalación de cookies e identificadores propios y de terceros y a través de herramientas para el análisis de uso de cuenta, podrá realizar actividades de seguimiento a los usuarios que utilizan su aplicación. Con estas herramientas, Mundo Network podrá recopilar información de cada usuario para el análisis de estadísticas e implementación de estrategias de comunicación y publicidad. Estas herramientas podrán realizar seguimiento de la configuración del usuario y hacen que su experiencia en la aplicación sea más práctica, reconociendo y recordando sus preferencias y ajustes.</p>
                     <p>En esta medida, Mundo Network podrá recopilar datos de uso, como la duración de uso, o datos demográficos como el origen, el sexo y la edad. Mundo Network usa esta información para fines analíticos. El usuario de Mundo Network podrá deshabilitar estas herramientas.</p>
                     <p>Las actividades de seguimiento adelantadas por Mundo Network también podrán realizarse dentro de la aplicación, para análisis interno, ejemplo, pero no exclusivamente para determinar tendencias y participación en la aplicación, tiempo de uso, preferencia, entre otros. Estas herramientas podrán ser desactivadas por el usuario ‘para conservar su privacidad. Ver más aquí.</p>
                     <p><b>Análisis de dato</b></p>
                     <p>El usuario al crear su cuenta y/o al hacer uso de la aplicación, acepta que Mundo Network puede suministrar, transferir, compartir y analizar los datos del giro ordinario de su negocio, con empresas aliadas, filiales, vinculadas o subordinadas de Mundo Network en España o cualquier otro país, esta información podrá ser usada para fines comerciales por parte de los terceros.</p>
                     <p>El usuario en cualquier momento puede solicitar a Mundo Network que detenga de forma indefinida el proceso de compartir sus datos con terceros, para esto debe realizar su solicitud al correo admin@MundoNetwork.com o comunicarse a través del chat de atención al cliente.</p>
                     <p><b>Términos Usados</b></p>
                     <p>El término "contrato" o "acuerdo" hace referencia a este contrato y a sus Términos y Condiciones.</p>
                     <p>El término "leyes aplicables" hace referencia a las leyes que se aplican en España para este tipo de contratos.</p>
                     <p>El término "sitio" o "sitio web" hace referencia al sitio donde se prestan todos los servicios que Mundo Network ofrece, sin tener en cuenta posibles terceros relacionados con Mundo Network.</p>
                     <p>El término "servicio" o “servicios” hace referencia a la aplicación que ofrece Mundo Network en su sitio web y que opera desde el dominio MundoNetwork.com. También hace referencia al uso de la página web de Mundo Network y su centro de soporte.</p>
                     <p>Los términos "Sistema", "Sistema de información", “Aplicativo”, “Software”, “Plataforma”, “Plataforma Mundo Network, hacen referencia al software web prestado como servicio por parte de la empresa Mundo Network, incluidos todos sus contenidos.</p>
                     <p>El término "titular de la cuenta" hace referencia a la persona a nombre de quien está la tarjeta de crédito / débito o el depósito bancario que se usó para registrar la cuenta en Mundo Network</p>
                     <p>El término “cuenta” hace referencia a la instancia o espacio creado por el titular de la cuenta para operar el software Mundo Network de acuerdo a su Plan adquirido.</p>
                     <p>Los términos “Institución” o “institución de educación” hacen referencia a las entidades para las cuales se presta el servicio.</p>
                     <p>El término "usuario" hace referencia a la persona que visita y usa el sitio web de Mundo Network y su aplicación, sea o no "titular de cuenta"</p>
                     <p>El término "usuario administrador" hace referencia al usuario que tiene la facultad de habilitar y crear nuevos usuarios en la plataforma Mundo Network, delimitándoles sus perfiles de acceso; el titular de la cuenta es un usuario administrador por defecto quien a su vez puede crear nuevos usuarios administradores.</p>
                     <p>El término "Plan" hace referencia a las condiciones de uso que tiene un usuario según el pago que haya efectuado.</p>
                     <p><b>Registro de Cuentas y Usuarios</b></p>
                     <p>Mundo Network presta un servicio de software que se accede a través de su sitio web www.Mundo Network.com y/o del dominio Mundo Network.com. Los titulares de las cuentas que accedan a este servicio deberán registrar una cuenta y brindar la información solicitada en los formularios que se habilitan a la hora de registrarla. Mundo Network da por entendido que cualquier información ingresada en estos formularios es hecha bajo juramento y por lo tanto exonera a Mundo Network de poseer información falsa sobre cualquier titular.</p>
                     <p>Para ser un usuario de la plataforma Mundo Network es necesario que el titular de la cuenta o usuario administrador delegado le asigne y le registre sus credenciales de acceso: usuario y contraseña, para su posterior uso; para ello, cada institución definirá las condiciones específicas que deba cumplir cada usuario a fin de otorgarle los medios de acceso y uso al sistema de información, quedando bajo su autonomía la creación, modificación o eliminación de sus usuarios.</p>
                     <p>Mundo Network permite el ingreso de una cantidad limitada de usuarios según el plan que cada titular o usuario de cuenta haya elegido al momento de registrar su cuenta. Mundo Network no permite, bajo ninguna circunstancia, que estos usuarios sean distintos de aquellos que el titular de la cuenta haya decidido habilitar como tales para el uso de la plataforma y estos no podrán ser reemplazados por otras personas que conozcan las credenciales para ingresar a la plataforma. De suceder una situación como ésta, Mundo Network no se hace responsable por el uso pernicioso de la información de la cuenta en contra del titular de la misma ni frente al usuario ni frente a terceros.</p>
                     <p><b>Derechos de Autor</b></p>
                     <p>Los derechos de autor sobre la plataforma Mundo Network y demás servicios agregados, son de titularidad de la empresa Mundo Network y bajo ninguna interpretación de estos términos y condiciones se entenderán transferidos al usuario.</p>
                     <p><b>Información de la cuenta</b></p>
                     <p>La plataforma Mundo Network es un aplicativo Web, el cual proporciona un sitio donde se alojan datos que el usuario administra bajo su cuenta y riesgo. Mundo Network vela por mantener la información de los usuarios, segura y toma las precauciones a su juicio necesarias para ello, mas no se responsabiliza por actos mal intencionado de terceros y las consecuencias de ello frente al usuario o frente a terceros.</p>
                     <p>El usuario será el único responsable de la cantidad y la calidad de la información tanto personal como de la gestión institucional ingresada, modificada y/o eliminada en el sistema de información para su adecuado funcionamiento y resultados arrojados, estando obligado a hacer uso sano y legal de la plataforma en los términos en que ha sido contratado el servicio y en virtud de ello, deberá tomar las medidas preventivas usuales en la actividad de la computación, con el fin de evitar que eventualmente se produzcan fallas que le causen cualquier tipo de daño o perjuicio, bien sea a la institución que representa o a terceros. El titular de la cuenta, quien adquiere las credenciales iniciales con todos los privilegios de acceso al sistema Mundo Network, o su usuario administrador delegado deberá ejercer un adecuado control sobre los usuarios a los cuales les autorice acceso delimitándoles claramente sus autorizaciones y responsabilidades. En todo caso, Mundo Network queda exonerado de cualquier uso indebido de la información por parte de cualquier usuario.</p>
                     <p>El usuario de la plataforma Mundo Network manifiesta ser dueño de la información que ingresa en el sistema y bajo ninguna circunstancia esta información pasará a ser propiedad de Mundo Network, y de manera inversa, esta última sociedad es la única dueña de la plataforma sobre la cual el usuario ingresa la información, sin que respecto de ésta se considera surtida transferencia alguna en razón de éste contrato. Si el usuario da por terminado el contrato, a partir de su finalización, contará con un plazo de 45 días calendario para descargar una copia de seguridad con la última versión de la información estructurada almacenada en la plataforma, en el formato XML, pero en ningún momento Mundo Network se obliga a entregar la misma en otro formato diferente ni a llevar a cabo ningún tipo de proceso de migración, ni mucho menos a efectuar un desarrollo para que la información pueda ser analizada, ingresada o digitalizada en cualquier otro software.</p>
                     <p>Adicional a lo anterior, Mundo Network no se responsabiliza por el mal diligenciamiento de un formulario o por la información que erróneamente suministre el usuario al momento de realizar un trámite o de ingresar la información al software.</p>
                     <p><b>Seguridad de la Cuenta</b></p>
                     <p>Mundo Network vela por la seguridad de la contraseña que provea el titular de cuenta y los usuarios a la hora de registrar una cuenta en la plataforma y garantiza que tomará las medidas que se encuentren a su alcance para que esta contraseña no sea vista por terceros, mas no puede arrogarse la responsabilidad de garantizar su confidencialidad. Por otro lado, Mundo Network no se responsabiliza por el mal uso de la contraseña por parte del usuario ni por el uso de contraseñas que sean fáciles de descifrar, asumiendo que siempre que se acceda al sistema, lo hace el usuario directamente.</p>
                     <p><b>Terminación e Interrupción del Servicio</b></p>
                     <p>Mundo Network se reserva el derecho de terminar el servicio en cualquier momento, tanto de manera permanente como temporal, para aquellos casos en los que se deban realizar pagos sucesivos.</p>
                     <p>Mundo Network podrá terminar de manera unilateral la cuenta de un usuario en los siguientes escenarios: (i) En caso de que el usuario utilice los servicios prestados por Mundo Network para fines contrarios a la ley, especialmente aquellos que contraríen derechos de propiedad intelectual de terceros, de Mundo Network o de otros usuarios; (ii) En caso de que Mundo Network encuentre que el usuario está haciendo uso de su cuenta para la transmisión de programas malignos como virus, malwares, spywares, troyanos o similares, que puedan comprometer el debido funcionamiento de la plataforma de Mundo Network o que perjudiquen a terceros; (iii) Cuando existan elementos que permitan inferir a Mundo Network que el usuario no cuenta con la edad mínima para contratar los Servicios, en los términos de las condiciones preliminares de este contrato.</p>
                     <p>Mundo Network se reserva el derecho a decidir si el contenido publicado por los usuarios, al igual que el material de texto o fotográfico que sea cargado a la página web de Mundo Network resulta apropiado y se ajusta a las condiciones. En éste sentido, Mundo Network podrá impedir la publicación y comercialización de contenido que infrinja derechos de imagen, de habeas data y de privacidad de terceros, así como aquellos que resulten ofensivos, difamatorios o que constituyan infracciones a la ley.</p>
                     <p><b>Operación del Sitio</b></p>
                     <p>Mundo Network llevará a cabo las gestiones que a su juicio estime conducentes, tendientes a que la plataforma siempre esté disponible para el usuario, pero no garantiza lo anterior, tanto por los daños en las comunicaciones, por actos de terceros, mantenimiento o reestructuración u otro tipo de actos que se escapen del alcance y responsabilidad directa de Mundo Network. No obstante lo anterior, Mundo Network garantiza a los usuarios que pagan por el servicio, que el software estará disponible desde cualquier lugar del mundo que permita una conexión a internet, siempre y cuando el usuario recuerde las credenciales de su cuenta y las condiciones de prestación del servicio de conexión a Internet por parte de cada proveedor, lo permitan.</p>
                     <p><b>Política Comunicacional</b></p>
                     <p>Al registrar una cuenta con Mundo Network el titular de la cuenta debe introducir un email y un teléfono de contacto, así como registrar todos aquellos datos que el software le solicite a fin de determinar no solo su identificación, sino aquello que le permita al software procesar la información que el mismo usuario diligencie o ingrese. Al hacer esto, acepta recibir todos los correos y llamadas con información sobre el uso de la plataforma Mundo Network, información promocional u otro tipo de información procesada o enviada por Mundo Network. No obstante lo anterior, Mundo Network no podrá utilizar en beneficio suyo o de terceros, la información que haya ingresado el usuario, sin embargo, podrá utilizar la base de datos de las empresas o usuarias con fines publicitarios o comerciales para sí o para terceros, sin que por ello deba participar de ingreso alguno a los usuarios. El usuario podrá solicitar que sus datos dejen de ser compartidos en cualquier momento y por medio de los canales establecidos y/o a la siguiente dirección de correo electrónico: admin@MundoNetwork.com</p>
                     <p>Esta cláusula se interpretará sin detrimento de la autorización de uso de información a que se refiere el título “Política de Privacidad”. La autorización a que se refiere ésta cláusula podrá ser revocada por el usuario en cualquier tiempo escribiendo a la siguiente dirección de correo electrónico: admin@MundoNetwork.com</p>
                     <p>Adicionalmente los usuarios tendrán habilitada la posibilidad de comunicarse con el equipo de Mundo Network en caso de que tengan preguntas o dudas por resolver, preguntas generales sobre su cuenta o sobre el software como tal. Para los casos anteriores, deberán escribir a admin@MundoNetwork.com o utilizar la pestaña de soporte disponible en la aplicación.</p>
                     <p><b>Comentarios y Preguntas</b></p>
                     <p>En caso de existir consultas, quejas o reclamos sobre la información contenida en el presente documento de Términos y Condiciones, por favor escribir al correo admin@MundoNetwork.com, utilizando como asunto: Comentario Términos y Condiciones.</p>
                  </div>

               </div>
            </div>
         </div>
      </div>
   </div>
   </div>
   <!-- ============ Related product Section Ends Here========== -->
   <!-- ================ footer Section start Here =============== -->
   <?php echo view("footer"); ?>
   <!-- ================ footer Section end Here =============== -->
   <!-- All Needed JS -->
</body>